spring:
  datasource:
    url: jdbc:mysql://81.70.49.73:3306/micro_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: mallUser
    password: mallUser
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
    type: com.zaxxer.hikari.HikariDataSource